env:
  browser: true
  es2021: true
  node: true
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
rules:
  react/react-in-jsx-scope: 0
  no-unused-vars: 0
  react/prop-types: 0
  react/jsx-key: 0
